#Список всех эффектов: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
# Как правильно указать эффект?
# 1. Переходим на сайт и копируем айди нужного нам эффекта.
# 2. Пишем айди и ставим точку с запятой ";"
# 3. Указываем длительность эффекта (ДЛИТЕЛЬНОСТЬ УКАЗЫВАЕМ В СЕКУНДАХ!!!)
# 4. Указываем уровень эффекта.
# 5. Радуемся что всё работает!

EFFECTS:
  - BLINDNESS;200;1 #АЙДИ_ЭФФЕКТА;ДЛИТЕЛЬНОСТЬ;УРОВЕНЬ | TYPE_EFFECT;DURATION;LEVEL (ДЛИТЕЛЬНОСТЬ УКАЗЫВАЕМ В СЕКУНДАХ!!!)
#  - GLOWING;5;1